### ISSUE TITLE
zap_start does not start ZaProxy using Jenkins

### ISSUE THREAD

**Issue by AlbanAndrieu** [TeamPraxis/grunt-zaproxy#3]
Hi,

I have the following issue:

I am trying to integrate ZaProxy inside my Jenkins build 
Below is the sample
http://home.nabla.mobi:8380/jenkins/job/nabla-servers-bower-sample-nightly/

Based on the project
https://github.com/AlbanAndrieu/nabla-servers-bower-sample/

Jenkins user has zap in the PATH:
export PATH=$PATH:/zapSource/build/zap/

AND I have added 
Inject environment variables to the build process
with
Properties Content
PATH=$PATH:/zapSource/build/zap/

But still grunt-zaproxy cannot start zaproxy.
Maybe it is due to the fact that I am using : https://github.com/eirslett/frontend-maven-plugin

I have also tries to set ZAPROXY_HOME global environement variable to :
ZAPROXY_HOME=/workspace/divers/zaproxy-read-only/build/zap

Best regards,

Alban

**Comment by AlbanAndrieu** [comment]
Following issue helped to fix the current one: https://github.com/TeamPraxis/grunt-zaproxy/issues/2

Moreover in Jenkins you can use the plugin https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin

with the following settings:
Prepare an environment for the run
or 
Inject environment variables to the build process
with
Script Content -> PATH=$PATH:$ZAPROXY_HOME
ZAPROXY_HOME must be defined as a Jenkins global envrionement variable

In a pre-step
Add an Execute shell with the following:
echo PATH $PATH
ln -s ${ZAPROXY_HOME}/zap.sh zap.sh >/dev/null 2>&1 || true

**Comment by khamasaki** [comment]
Awesome, thanks for the info!

**Comment by Mouheb22** [comment]
hi @AlbanAndrieu , 
i'm a new user of ZAP and Jenkins, and i want to ask you : how did you get the alerts results of zap scanning in ZAP Scanning Report ( http://home.nabla.mobi:8380/jenkins/job/nabla-servers-bower-sample-nightly/ZaProxy_Report/ )
