### ISSUE TITLE
ZAP Stop task fails when an alert is found

### ISSUE THREAD

**Issue by mario-areias** [TeamPraxis/grunt-zaproxy#6]
When the ZAP finds an alert which is not ignored, it breaks the zap_stop task.

I know this is explicit in the documentation, however, it can cause problems and misunderstanding. I create a possible solution which I will link here. Any feedback is appreciated :+1:

**Comment by khamasaki** [comment]
Fixed by 98724dc94d1cd17447184c6f4ffd323d845ca7c8. New version published to npm. Thanks again!
